<?xml version="1.0" encoding="utf-8"?><Database Name="HandleManager" Class="HandleManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LIBGRTOBADZIST;Initial Catalog=HandleManager;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HandleManagerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HandleActions" Member="HandleActions">
    <Type Name="HandleAction">
      <Column Name="handle" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="target" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="target_type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[desc]" Member="desc" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="netid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="action" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>